language: php

php:
  - 7.0
  - 7.1
  - 7.2
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
# codeception
  - travis_retry composer global require "codeception/codeception=2.2.*" "codeception/specify=*" "codeception/verify=*"
# setup application:
  - |
    composer test-scaffold

script:
  - |
    composer test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)